In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("heart.csv")

In [13]:
categorical_columns = [
    "sex",
    "cp",
    "fbs",
    "restecg",
    "exang",
    "slope",
    "ca",
    "thal"
]

In [4]:
category_maps = {}

In [14]:
def manual_encoding(data, columns, category_maps):

    encoded_data = data.copy()

    for column in columns:

        if column not in category_maps:
            category_maps[column] = {}

        encoded_values = []

        for value in encoded_data[column]:

           
            if value not in category_maps[column]:

                new_number = len(category_maps[column])

                category_maps[column][value] = new_number

            encoded_values.append(
                category_maps[column][value]
            )

        encoded_data[column] = encoded_values

    return encoded_data, category_maps

In [15]:
data, category_maps = manual_encoding(
    data,
    categorical_columns,
    category_maps
)

In [16]:
data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,1,1,3,0
1,53,1,0,140,203,1,0,155,1,3.1,2,2,3,0
2,70,1,0,145,174,0,1,125,1,2.6,2,2,3,0
3,61,1,0,148,203,0,1,161,0,0.0,1,0,3,0
4,62,0,0,138,294,1,1,106,0,1.9,0,3,2,0

In [17]:
category_maps

{'sex': {1: 0, 0: 1},
 'cp': {0: 0, 1: 1, 2: 2, 3: 3},
 'fbs': {0: 0, 1: 1},
 'restecg': {1: 0, 0: 1, 2: 2},
 'exang': {0: 0, 1: 1},
 'slope': {2: 0, 0: 1, 1: 2},
 'ca': {2: 0, 0: 1, 1: 2, 3: 3, 4: 4},
 'thal': {3: 0, 2: 1, 1: 2, 0: 3, 99: 4}}

In [18]:
future_data = data.head(3).copy()
future_data.loc[0, "thal"] = 99

In [19]:
future_data, category_maps = manual_encoding(
    future_data,
    categorical_columns,
    category_maps
)

In [20]:
future_data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,0,0,125,212,0,0,168,0,1.0,2,2,4,0
1,53,0,0,140,203,1,1,155,1,3.1,0,0,0,0
2,70,0,0,145,174,0,0,125,1,2.6,0,0,0,0

In [21]:
category_maps["thal"]

{3: 0, 2: 1, 1: 2, 0: 3, 99: 4}