In [2]:
import numpy as np
import pandas as pd

In [3]:
data = pd.read_csv("heart.csv")

In [4]:
data

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [13]:
 median_bps=data["trestbps"].median()
median_bps

130.0

In [8]:
q1 = data["trestbps"].quantile(0.25)
q1

np.float64(120.0)

In [9]:
q2 = data["trestbps"].quantile(0.75)
q2

np.float64(140.0)

In [12]:
q = q2-q1
q

np.float64(20.0)

In [15]:
data["trestbps_robust"] = (data["trestbps"] - median_bps) /q
q

np.float64(20.0)

In [19]:
data["oldpeak_log"] = np.log1p(data["oldpeak"])

In [20]:
a_chol = data['chol'].quantile(0.05)
a_chol

np.float64(175.0)

In [21]:
b_chol = data['chol'].quantile(0.95)
b_chol

np.float64(330.0)

In [22]:
data["chol_clipped"] = data["chol"].clip(lower=a_chol, upper=b_chol)

In [24]:
min_chol = data["chol_clipped"].min()
max_chol = data["chol_clipped"].max()

In [25]:
data["chol_winsor_minmax"] = (data["chol_clipped"] - min_chol) / (max_chol - min_chol)

In [27]:
data[["trestbps_robust", "oldpeak_log", "chol_winsor_minmax"]].head()

   trestbps_robust  oldpeak_log  chol_winsor_minmax
0            -0.25     0.693147            0.238710
1             0.50     1.410987            0.180645
2             0.75     1.280934            0.000000
3             0.90     0.000000            0.180645
4             0.40     1.064711            0.767742